### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by xelra** [ritave/xeventbind#2]
Please feel free to close this issue immediately.

Since there's no "thank you" feature on GitHub, I'm creating this issue to properly thank you for this tool. 
I'm using it to get rid of one of the biggest annoyances when using i3wm in a virtual machine. With this tool I can resize the desktop wallpaper and restart conky, whenever the screen resolution changes.

Thank you!

**Comment by ritave** [comment]
Hah, I see it's solving the same problem I had - glad you enjoy it!
